require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GameLevelPermissionsController do

  # This should return the minimal set of attributes required to create a valid
  # GameLevelPermission. As you add validations to GameLevelPermission, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "game_level" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GameLevelPermissionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all game_level_permissions as @game_level_permissions" do
      game_level_permission = GameLevelPermission.create! valid_attributes
      get :index, {}, valid_session
      assigns(:game_level_permissions).should eq([game_level_permission])
    end
  end

  describe "GET show" do
    it "assigns the requested game_level_permission as @game_level_permission" do
      game_level_permission = GameLevelPermission.create! valid_attributes
      get :show, {:id => game_level_permission.to_param}, valid_session
      assigns(:game_level_permission).should eq(game_level_permission)
    end
  end

  describe "GET new" do
    it "assigns a new game_level_permission as @game_level_permission" do
      get :new, {}, valid_session
      assigns(:game_level_permission).should be_a_new(GameLevelPermission)
    end
  end

  describe "GET edit" do
    it "assigns the requested game_level_permission as @game_level_permission" do
      game_level_permission = GameLevelPermission.create! valid_attributes
      get :edit, {:id => game_level_permission.to_param}, valid_session
      assigns(:game_level_permission).should eq(game_level_permission)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GameLevelPermission" do
        expect {
          post :create, {:game_level_permission => valid_attributes}, valid_session
        }.to change(GameLevelPermission, :count).by(1)
      end

      it "assigns a newly created game_level_permission as @game_level_permission" do
        post :create, {:game_level_permission => valid_attributes}, valid_session
        assigns(:game_level_permission).should be_a(GameLevelPermission)
        assigns(:game_level_permission).should be_persisted
      end

      it "redirects to the created game_level_permission" do
        post :create, {:game_level_permission => valid_attributes}, valid_session
        response.should redirect_to(GameLevelPermission.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved game_level_permission as @game_level_permission" do
        # Trigger the behavior that occurs when invalid params are submitted
        GameLevelPermission.any_instance.stub(:save).and_return(false)
        post :create, {:game_level_permission => { "game_level" => "invalid value" }}, valid_session
        assigns(:game_level_permission).should be_a_new(GameLevelPermission)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GameLevelPermission.any_instance.stub(:save).and_return(false)
        post :create, {:game_level_permission => { "game_level" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested game_level_permission" do
        game_level_permission = GameLevelPermission.create! valid_attributes
        # Assuming there are no other game_level_permissions in the database, this
        # specifies that the GameLevelPermission created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GameLevelPermission.any_instance.should_receive(:update).with({ "game_level" => "" })
        put :update, {:id => game_level_permission.to_param, :game_level_permission => { "game_level" => "" }}, valid_session
      end

      it "assigns the requested game_level_permission as @game_level_permission" do
        game_level_permission = GameLevelPermission.create! valid_attributes
        put :update, {:id => game_level_permission.to_param, :game_level_permission => valid_attributes}, valid_session
        assigns(:game_level_permission).should eq(game_level_permission)
      end

      it "redirects to the game_level_permission" do
        game_level_permission = GameLevelPermission.create! valid_attributes
        put :update, {:id => game_level_permission.to_param, :game_level_permission => valid_attributes}, valid_session
        response.should redirect_to(game_level_permission)
      end
    end

    describe "with invalid params" do
      it "assigns the game_level_permission as @game_level_permission" do
        game_level_permission = GameLevelPermission.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GameLevelPermission.any_instance.stub(:save).and_return(false)
        put :update, {:id => game_level_permission.to_param, :game_level_permission => { "game_level" => "invalid value" }}, valid_session
        assigns(:game_level_permission).should eq(game_level_permission)
      end

      it "re-renders the 'edit' template" do
        game_level_permission = GameLevelPermission.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GameLevelPermission.any_instance.stub(:save).and_return(false)
        put :update, {:id => game_level_permission.to_param, :game_level_permission => { "game_level" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested game_level_permission" do
      game_level_permission = GameLevelPermission.create! valid_attributes
      expect {
        delete :destroy, {:id => game_level_permission.to_param}, valid_session
      }.to change(GameLevelPermission, :count).by(-1)
    end

    it "redirects to the game_level_permissions list" do
      game_level_permission = GameLevelPermission.create! valid_attributes
      delete :destroy, {:id => game_level_permission.to_param}, valid_session
      response.should redirect_to(game_level_permissions_url)
    end
  end

end
